### ISSUE TITLE
Using simxGetObjectPosition and similar functions

### ISSUE THREAD

**Issue by P4STA** [SeveQ/remoteApiNETWrapper#3]
Greetings

I don't understand the use of simxGetObjectPosition. How do I get the position out of it?
I have the communication running, simxStart returns 0. And I am able to get object handles through simxGetObjectHandle. But when I try to use simxGetObjectPosition, it returns novalue_flag.

```
using System;
using remoteApiNETWrapper;

namespace ConsoleApplication2
{
    class Program
    {
        static void Main(string[] args)
        {
            simx_error err;
            int clientID = VREPWrapper.simxStart("127.0.0.1", 19999, true, true, 5000, 5);
            Console.WriteLine("clientID: " + clientID);
            int wurfel;
            VREPWrapper.simxGetObjectHandle(clientID, "wurfel", out wurfel, simx_opmode.oneshot_wait);
            Console.WriteLine("wurfel handle: " + wurfel);
            float[] pos = new float[3];
            err =  VREPWrapper.simxGetObjectPosition(clientID, wurfel, -1, pos, simx_opmode.streaming);
            Console.WriteLine("err: " + err.ToString());
            Console.ReadLine();
            VREPWrapper.simxFinish(clientID);
        }
    }
}
```

I've also changed DLLInports from
`[DllImport("remoteApi.dll")]`
to
`[DllImport("remoteApi.dll", CallingConvention = CallingConvention.Cdecl)]`
if that has anything to do with it.

**Comment by horverno** [comment]
for `simxGetObjectPosition` try `simx_opmode.oneshot_wait`

i have a short example: [https://github.com/horverno/sze-academic-robotics-projects/tree/master/VrepCsharpInteroperation](https://github.com/horverno/sze-academic-robotics-projects/tree/master/VrepCsharpInteroperation)

**Comment by HWiese1980** [comment]
Just noticed this issue, sorry. Is it solved? Can it be closed?

**Comment by P4STA** [comment]
Yes. The different `simx_opmode` worked. Thanks

**Comment by HWiese1980** [comment]
Great! :-)
