### ISSUE TITLE
Read Joint Position on UI (Windows Forms or WPF)

### ISSUE THREAD

**Issue by wbadry** [SeveQ/remoteApiNETWrapper#4]
Hi,
I'm using your code port and currently adding XML comments and some encapsulation of functions like you did with signal functions.

My problem is although I followed same method in remote API to read stream data from joints, I was unable to update any UI controls even using Dispatcher technique. Data is received correctly and I can log it on output window but UI thread hangs until receiving last value.

I would appreciate if you have any simple demo showing how to carry even a single joint read and update a label on Windows F|orms or WPF app.

Thanks

**Comment by HWiese1980** [comment]
Hey, just saw your issue. As you can see I haven't touched this project in quite a while... and I'm a bit rusty when it comes to Windows Forms, so, coming up with a simple demo might take some time... give me a couple of days and I'll see what I can do. 

Just one thing... if you could remind me of this occasionally, that would be great. I'm pretty busy during the week, and hence during the weekend I usually try to relax and tend to forget a lot of stuff. ;-) 

I'll see what I can do.

**Comment by wbadry** [comment]
@HWiese1980 Thanks for your response. I highly appreciate your help. After a bit of reading about threading, I tackled the problem using thread pool (**Task.Run Method**). Thanks again and have a nice day.
